// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyynMmEhN7OMDECwAWE8OIJr8QgkMMZ9g',
    appId: '1:97423231459:web:eb623995afa9b54858f8d6',
    messagingSenderId: '97423231459',
    projectId: 'chattingapp-b3e02',
    authDomain: 'chattingapp-b3e02.firebaseapp.com',
    storageBucket: 'chattingapp-b3e02.firebasestorage.app',
    measurementId: 'G-152H7QW6Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-IDqk0c1OTdeGw2PaXPslt-eIE6qDOM',
    appId: '1:97423231459:android:438a7fcb0d0cfcdd58f8d6',
    messagingSenderId: '97423231459',
    projectId: 'chattingapp-b3e02',
    storageBucket: 'chattingapp-b3e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12TfmCXbP8rW-IQc2l0WqwUDCbwDXAbI',
    appId: '1:97423231459:ios:d9187275773ffcb758f8d6',
    messagingSenderId: '97423231459',
    projectId: 'chattingapp-b3e02',
    storageBucket: 'chattingapp-b3e02.firebasestorage.app',
    iosBundleId: 'com.example.chatNew',
  );
}
